version: '2'
services:
   
    redis:
      container_name: redis-cache
      image: redis
      restart: always
      expose:
        - 6379

    server:
      build: .
      restart: always
      depends_on:
        - redis
      ports:
        - "8000:8000"
      volumes:
        - ./config:/config
      environment:
        - RD_HOST=redis
        - DB_PORT=6379
        - HTTP_PORT=8000
        - GIN_MODE=release